### ISSUE TITLE
CreateDefaultBuilder doesn't work with command line "dotnet run -urls http://xxxx:xxxx"

### ISSUE THREAD

**Issue by wjf108** [aspnet/MetaPackages#226] opened 2017-08-28 15:33 UTC
WebHost.cs line:173
```javascript 
public static IWebHostBuilder CreateDefaultBuilder(string[] args)
{
    ....
    if (args != null)
    {
        config.AddCommandLine(args);
    }
    ....
}
```

It doesn't work with "dotnet run -urls http://xxxx:xxxx", unless I add the following code manually:

```javascript 
public static void Main(string[] args)
        {
            var commandConfig = new ConfigurationBuilder()
                .AddCommandLine(args)
                .Build();
            WebHost.CreateDefaultBuilder(args)
                .UseConfiguration(commandConfig)
                .UseStartup<Startup>()
                .Build()
                .Run();
        }
```

**Comment by Tratcher** [comment] 2017-08-28 16:30
Duplicate of https://github.com/aspnet/MetaPackages/issues/221

**Closed by Tratcher** 2017-08-28 16:30 UTC
Labels: duplicate
